apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 3        # default replica count
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: web
          image: nginx:1.25
          ports:
            - containerPort: 80
